# Generated by Django 4.1.1 on 2022-09-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='test',
        ),
    ]
